services:
  lms:
    image: node:18
    platform: linux/amd64
    command: sh -c "cd /app/ && npm start"
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
      - ./public:/app/public
      - ./src:/app/src
      - ./.babelrc:/app/.babelrc
      - ./jsconfig.json:/app/jsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    env_file:
      - .env