services:
  lms:
    image: node:18
    platform: linux/amd64
    command: sh -c "cd /app/ && npm install && npm run dev"
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - node_modules:/app/node_modules
      - ./public:/app/public
      - ./src:/app/src
      - ./.babelrc:/app/.babelrc
      - ./jsconfig.json:/app/jsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    environment:
      NODE_ENV: development
      DB_NAME: acloandb_prod
      DB_URL: mongodb+srv://amber-admin:amberlms@cluster0.gborljd.mongodb.net/?retryWrites=true&w=majority
      DEV_URL: http://localhost:3000
      LOCAL_DB_NAME: acloandb-staging
      LOCAL_DB_URL: mongodb+srv://amber-admin:amberlms@cluster0.gborljd.mongodb.net/?retryWrites=true&w=majority
      NEXT_PUBLIC_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000/api/
      NEXT_PUBLIC_PATHS: /login,/register,/forgot-password
      NEXT_PUBLIC_IMAGE_HOST: http://localhost:3000
      NEXT_PUBLIC_LOCAL_HOST: localhost
      NEXT_PUBLIC_GA_ID: G-YWQQS28LLX
      HASURA_URL: http://188.166.225.198:8080
      HASURA_ADMIN_SECRET: lms_01

volumes:
  node_modules: