# NOTE: If not present, create the network using:
#  docker network create services-network
networks:
  default:
    name: services-network
    external: true

services:
  lms:
    image: node:18
    platform: linux/amd64
    deploy:
      replicas: 3
    command: sh -c "cd /app/ && npm start"
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
      - ./public:/app/public
      - ./src:/app/src
      - ./.babelrc:/app/.babelrc
      - ./jsconfig.json:/app/jsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf