### v1 login
POST http://localhost:3000/api/authenticate
Content-Type: application/json

{
  "username": "BMcebucity1@ambercashph.com",
  "password": "super_PassAC_24"
}

> {% client.global.set("auth_token", response.body.user.token); %}

### v1 logout
GET http://localhost:3000/api/authenticate?user=639e848092731e1d11fb6fd2
Content-Type: application/json

### v2 login
POST http://localhost:3000/api/v2/authenticate
Content-Type: application/json

{
  "username": "admin@ambercashph.com",
  "password": "superAmber09876"
}

### v2 logout
GET http://localhost:3000/api/v2/authenticate?user=639e848092731e1d11fb6fd2
Content-Type: application/json
