@apiUrl=http://localhost:3000/api/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTI5NzU1MDAsImV4cCI6MTcxMjk4OTkwMH0.Syjc7WZKT-heSOENSD4ZS-4Ko23jM2FHBIqqg5VQ160

### Get Data
GET {{apiUrl}}/other-transactions/badDebtCollection?_id=65cc3dc8ecc5a117cc1b494c
Content-Type: application/json
Authorization: Bearer {{token}}
