@apiUrl=http://localhost:3000/api/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTI5Mjc1ODUsImV4cCI6MTcxMjk0MTk4NX0.1QznK3_laJXRAU6WCd60efpy-v6yLw4GgFuAvYmZynE

### Get Data
GET {{apiUrl}}/v2/other-transactions/badDebtCollection?_id=65cc3dc8ecc5a117cc1b494c
Content-Type: application/json
Authorization: Bearer {{token}}
