GET http://localhost:3000/api/branches/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTExMTQyOTAsImV4cCI6MTcxMTEyODY5MH0.VqcJ090NTvG2fQrTdjmYj7wFijp9onsaKL2_EqTntGc

### v1
GET http://localhost:3000/api/branches?code=B001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTExMTQyOTAsImV4cCI6MTcxMTEyODY5MH0.VqcJ090NTvG2fQrTdjmYj7wFijp9onsaKL2_EqTntGc

### v2
GET http://localhost:3000/api/v2/branches/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTExMTQyOTAsImV4cCI6MTcxMTEyODY5MH0.VqcJ090NTvG2fQrTdjmYj7wFijp9onsaKL2_EqTntGc


### v2
GET http://localhost:3000/api/v2/branches?code=B001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllODQ4MDkyNzMxZTFkMTFmYjZmZDIiLCJpYXQiOjE3MTExMTQyOTAsImV4cCI6MTcxMTEyODY5MH0.VqcJ090NTvG2fQrTdjmYj7wFijp9onsaKL2_EqTntGc

