services:
  hasura:
    image: hasura/graphql-engine:v2.37.0
    volumes:
      - ./hasura/metadata:/hasura-metadata
      - ./hasura/migrations:/hasura-migrations
    expose:
      - "${HASURA_PORT:-8080}"
    ports:
      - "${HASURA_PORT:-8080}:${HASURA_PORT:-8080}"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5433/acloandb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE:-true}"
      HASURA_GRAPHQL_DEV_MODE: "${HASURA_GRAPHQL_DEV_MODE:-true}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-lms_01}
    command:
      - graphql-engine
      - serve