name: Deploy to Production Server
on:
  push:
    branches:
      - master
jobs:
  deploy-latest-code:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_KEY}}
          script: |
            cd /home/lmsadmin/lms
            git checkout master
            git pull origin master
            npm install
            npm run build 
            pm2 restart lms
